name: Build Check
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - '.vscode/**'
      - '.husky/**'
      - '.env'
      - '.gitignore'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - '.vscode/**'
      - '.husky/**'
      - '.env'
      - '.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
          cache: 'npm'

      - name: Cache NPM Dependencies
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Check Cache
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm i

      - name: Build
        run: |
          npm install 
          npm run build
